const x = 2;

try {
  x = 3;
  console.log(x);
} catch (error) {
  console.log(error.message);
}

console.log("Hi");

console.log("Hello");

console.log(2 + 3);
